### PR TITLE
Update runtime to 5.13

### PR DESCRIPTION
**Pull request by muelli**

### CODE REVIEW

**Comment by christian-rauch** [comment]
@muelli Is this just for testing? Otherwise, I would stay with the long term supported version 5.12 and switch to the next long term version (5.18) once it has been released.

**Comment by muelli** [comment]
No, not for testing. Rather for getting rid of the only consumer of the 5.12 runtime on my machine.
I wasn't aware of 5.12 being LTS. Do you happen to have a reference?
Anyway, feel free to close or ignore this patch. Or to merge to beta, if you don't have another use that channel :)

**Comment by christian-rauch** [comment]
> Rather for getting rid of the only consumer of the 5.12 runtime on my machine.

... and someone else will be annoyed to have the 5.13 runtime installed just for this app :-)

Is there data on how these runtimes are used? I.e. how many apps use version 5.12/5.13?

> I wasn't aware of 5.12 being LTS. Do you happen to have a reference?

I am not sure about the runtime, but at least the desktop and its libraries are marked as LTS for 5.12 and 5.18: https://community.kde.org/Schedules/Plasma_5. These versions coincide with the Ubuntu LTS releases.

**Comment by hfiguiere** [comment]
See #5

**Comment by lionirdeadman** [comment]
> ... and someone else will be annoyed to have the 5.13 runtime installed just for this app :-)
>
> Is there data on how these runtimes are used? I.e. how many apps use version 5.12/5.13?

FWIW here is a summary of stats that I compile here : https://github.com/lionirdeadman/fp-stats
```
KDE:

org.kde.Platform//5.15              : 286   (85.4%)
org.kde.Sdk//5.15                   : 3     (0.9 %)
org.kde.Platform//5.14              : 23    (6.9 %)
org.kde.Platform//5.13              : 1     (0.3 %)
org.kde.Platform//5.12              : 20    (6.0 %)
org.kde.Platform//5.11              : 1     (0.3 %)
org.kde.Platform//5.9               : 1     (0.3 %)
org.kde.*//*:                       : 335 
```

**Pull request closed without merging**
