### PR TITLE
Update runtime to 5.15-21.08

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
Apparently requires Clang to build.

**Comment by christian-rauch** [comment]
The "Cork Boolean Library" needs clang https://github.com/cloudcompare/cork#dependencies-maclinux.

@hfiguiere What's the advantage of changing from 5.15 to 5.15-21.08? They contain the same Qt version. Was clang part of the previous runtime version (5.15) and removed in the newer (5.15-21.08)? This worked without issues before.

Do we have to use one of these extensions https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm11 for this? Building clang from source just for cork seems like a huge overhead to me.

**Comment by christian-rauch** [comment]
bot, build

**Comment by christian-rauch** [comment]
The `clang++` executable was removed from the `org.kde.Sdk`.

I have both versions installed:
```
$ ls -1 /var/lib/flatpak/runtime/org.kde.Sdk/x86_64
5.15
5.15-21.08
```
but `clang++` is only in the version `5.15` and the llvm extension:
```
$ find /var/lib/flatpak/runtime -name clang++
/var/lib/flatpak/runtime/org.freedesktop.Sdk.Extension.llvm12/x86_64/21.08/272e805907660c4fb3c1d668982278e5a8445802d1bef01415bd21caf905c70c/files/bin/clang++
/var/lib/flatpak/runtime/org.kde.Sdk/x86_64/5.15/7584eda1a3e29cb4f5310942a1b1ed55a8823a54320f2cb7dea128db280486d8/files/bin/clang++
```

However, the build still fails to find the `clang++` executable.

@hfiguiere Do you have to set environment variables or something to make the flatpak builder aware of the `llvm12` extension?

**Comment by hfiguiere** [comment]
it's in the readme

https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm12/blob/branch/21.08/README.md

**Comment by hfiguiere** [comment]
The C++ patch fix a bug from upstream that cause a build failure.

**Comment by christian-rauch** [comment]
> The C++ patch fix a bug from upstream that cause a build failure.

Thanks. I create an issue for that at https://github.com/asmaloney/libE57Format/issues/93. The `<limits>` header is missing because of `#if __GNUC__ >= 11`. If we just remove that `ifdef`, it should also work.

**Pull request merged**
