### PR TITLE
Enable building of RDB IO plugin

### PR DESCRIPTION
**Pull request by NeroBurner**
Enable the build for the IO-Plugin RDB and tell CMake to fetch the dependency for building the library

The following three options are enabled:
- `PLUGIN_IO_QRDB`: enable the building of the plugin
- `PLUGIN_IO_QRDB_FETCH_DEPENDENCY` tell CMake to fetch the build and runtime dependency rdb library
- `PLUGIN_IO_QRDB_INSTALL_DEPENDENCY`: add the rdb library dependency to the install targets to be available for the distributed package

---

I don't know if this is the right way to do it for a flatpak build, it's the way that works for me to build the IO RDB plugin

### CODE REVIEW

**Comment by NeroBurner** [comment]
Wow, that was FAST! Thanks a lot!

**Comment by dgirardeau** [comment]
The PR was short ;)

**Comment by christian-rauch** [comment]
Usually, the @flathubbot should create a test build like in https://github.com/flathub/org.cloudcompare.CloudCompare/pull/6#issuecomment-977003385. I am not sure why this did not happen here.

With this PR merge, the master branch will not build anymore: https://flathub.org/builds/#/builders/10/builds/8199.

**Comment by dgirardeau** [comment]
Ah! I trusted the CI green light... well absence of red light 😅

**Comment by dgirardeau** [comment]
Should this commit be reverted then? Or @NeroBurner  can you fix it easily?

**Comment by christian-rauch** [comment]
@bilelmoussaoui I don't seem to have the right to change the settings of this repo. Can I/you set up the repo such that it is not possible to merge if the @flathubbot fails to build the app? Do you have an idea why the @flathubbot did not start a build with their PR automatically?

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui I don't seem to have the right to change the settings of this repo. Can I/you set up the repo such that it is not possible to merge if the @flathubbot fails to build the app? Do you have an idea why the @flathubbot did not start a build with their PR automatically?

Sometimes the buildbot doesn't receive the event to trigger a build for various reasons :/ in such case you can trigger it (or any committer) by typing `bot, build` in a comment.

**Comment by christian-rauch** [comment]
bot, build

**Comment by christian-rauch** [comment]
Cool, that worked.

@NeroBurner I am going to revert this. The build fails because `repository.riegl.com` is not available (to fetch https://repository.riegl.com/software/libraries/rdblib/current/linux/rdblib--x86_64-linux.tar.gz). I assume this is hardcoded in the CMake script so it is probably not easy to fix. Can you submit a new PR once this issue is resolved, and if required trigger the bot manually using the comment `bot, build`.

**Comment by NeroBurner** [comment]
Thanks for the headup. Somehow the `version.txt` didn't get downloaded in the flatpak build (URL: https://repository.riegl.com/software/libraries/rdblib/current/version.txt )

Compiling locally the commit
```
c0ed1784955b71d6a526a8a72622de03b2c93f93 (HEAD -> master, upstre
am/master)
Author: Daniel Girardeau-Montaut <daniel.girardeau@gmail.com>
Date:   Sun Nov 28 22:33:42 2021 +0100

    Bug fix: trying to merge several clouds, some being ancestors of the others, could lead to a crash
```

with the following cmake command
```sh
cmake -S . -B _build -DCMAKE_BUILD_TYPE=Release -DPLUGIN_IO_QRDB=ON -DPLUGIN_IO_QRDB_FETCH_DEPENDENCY=ON -DPLUGIN_IO_QRDB_INSTALL_DEPENDENCY=ON
```

then the download is working as expected:
```
-- PLUGIN_IO_QRDB: downloading rdb_sdk version '2.3.7' from URL 'https://repository.riegl.com/software/libraries/rdblib/current/linux/rdblib-2.3.7-x86_64-linux.tar.gz'
-- PLUGIN_IO_QRDB: populated rdb_sdk and setting 'rdb_DIR' to '/home/gc/repos/CloudCompare/qRDBIO_deb/CloudCompare/_build_focal_amd64/_deps/rdb_sdk-src/interface/cpp'
-- rdb: providing targets rdbc, rdbcpp and rdbcpp-rtl
-- Added io plugin: QRDB_IO_PLUGIN
```

Does flatpak build limit the internet access curing CMake configuration?

**Comment by christian-rauch** [comment]
I see. The failing URL (https://repository.riegl.com/software/libraries/rdblib/current/linux/rdblib--x86_64-linux.tar.gz) is supposed to be version encoded. But this fails on the buildbot (`PLUGIN_IO_QRDB: downloading rdb_sdk version '' from URL`) because it cannot parse the version.

The buildbot reports `Couldn't resolve host 'repository.riegl.com'`. So even with a hardcoded version number or URL, CMake may fail to download a package from that URL. @NeroBurner Can you download `rdblib` manually via the flatpak manifest and use that instead?

@bilelmoussaoui Are there limitations on how and what CMake can download when used in a flatpak or with the @flathubbot?

**Comment by NeroBurner** [comment]
Trying over here https://github.com/flathub/org.cloudcompare.CloudCompare/pull/10

Feedback welcome if I'm doing something very hacky or stupid, got no experience with flatpak builds :sweat_smile:

**Pull request merged**
